version: "3"
services:
  front:
    build:
      context: ./frontend
    container_name: front-container
    ports:
      - "5173:5173"
    restart: unless-stopped

  backend:
    build:
      context: ./my-time-backend
    container_name: backend-container
    ports:
      - "3000:3000"
    restart: unless-stopped
