# Stage 1: Build the application
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
RUN npm run build

# Stage 2: Run the application
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy the "dist" folder from the builder stage
COPY --from=builder /usr/src/app/dist ./dist

# Copy the .env file
COPY .env ./

# Install production dependencies only
COPY package*.json ./
RUN npm install --only=production

# Expose the port on which the app will run
EXPOSE 3000

# Start the server using the production build
CMD ["npm", "run", "start:prod"]